# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
bundler_args: --binstubs

# Specify which ruby versions you wish to run your tests on, each version will be used
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
script: "bundle exec rake"
before_install:
  - gem update bundler
